language: python

python:
  - "3.6"

install:
  - pip install pipenv python-coveralls
  - pipenv install --dev
  - pipenv run pip install -e .

script: make travis

branches:
  only:
  - master

after_success:
  - coveralls

